language: generic
os: linux
sudo: required

services:
  - docker

before_install:
  - docker build -t vigilx/docker-react -f dockerfile.dev .

script:
  - docker run vigilx/docker-react npm run test -- --coverage

 
