language: generic
os: linux
sudo: required
dist: xenial
services:
  - docker

before_install:
  - docker build -t vigilx/docker-react -f dockerfile.dev .

script:
  - docker run -e CI=true vigilx/docker-react npm run test -- --coverage

 
