language: generic
os: linux
sudo: required
dist: xenial
services:
  - docker

before_install:
  - docker build -t vigilx/docker-react -f dockerfile.dev .

script:
  - docker run -e CI=true vigilx/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-257673020747"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
    